project_name: 'hw-02'
experiment_name: 'recommender-track'
n_epochs: 200
accelerator: 'gpu'
device: 0
monitor_metric: 'val_mae'
monitor_mode: 'min'

model_kwargs:
  d_model: 128     # размерность модели
  n_tracks: 50000  # количество треков
  n_users: 10000   # количество пользователей

optimizer: 'torch.optim.AdamW'
optimizer_kwargs:
  lr: 3e-3
  weight_decay: 1e-5

scheduler: 'torch.optim.lr_scheduler.ReduceLROnPlateau'
scheduler_kwargs:
  patience: 20000
  verbose: True

#scheduler: 'torch.optim.lr_scheduler.CosineAnnealingLR'
#scheduler_kwargs:
#  T_max: 10
#  eta_min: 1e-5

losses:
  - name: 'MSE'
    weight: 0.5
    loss_fn: 'torch.nn.MSELoss'
    loss_kwargs: {}

  - name: 'L1Loss'
    weight: 0.5
    loss_fn: 'torch.nn.L1Loss'
    loss_kwargs: {}

#  - name: 'KL'
#    weight: 0.01
#    loss_fn: 'torch.nn.KLDivLoss'
#    loss_kwargs: {'reduction': 'sum'}


data_config:
  data_path: 'data'
  need_prepare: True
  train_size: 0.99
  batch_size: 65536
  n_workers: 8